### ISSUE TITLE
AttributeError: type object 'Location' has no attribute '_update_orders'

### ISSUE THREAD

**Issue by Wizely99** [TimurKady/django-fast-treenode#6]
I am using treemodel in my Location model and on updating the tree I get the error below

Location.update_tree()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dante/miniconda3/envs/django/lib/python3.12/site-packages/treenode/models.py", line 148, in update_tree
    cls._update_orders()
    ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Location' has no attribute '_update_orders'

**Comment by TimurKady** [comment]
Yes, sorry, these are artifacts of old code. Comment out line 146. I'll fix the code soon.

I would like to draw your attention to the fact that if you started a project using this library from the very beginning, you do not need to call update_tree. This method only needs to be called once when migrating from django-treenode to django-fast-treenode

**Comment by TimurKady** [comment]
Fixed

**Comment by Wizely99** [comment]
Thanks alot for your time and work.

**Comment by TimurKady** [comment]
Thank you too! Enjoy using it!
