### ISSUE TITLE
cache set by `@cached_tree_method`  decorator is never invalidated or am I missing something?

### ISSUE THREAD

**Issue by Wizely99** [TimurKady/django-fast-treenode#7]

**Comment by TimurKady** [comment]
The `@cached_tree_method` decorator is used to cache the results of methods associated with object trees. The key cache is based on the node's `closure_path`, which means that each unique tree method in the context of a particular node will have its own cache.

The cache itself is invalidated in cases where methods that potentially change the tree structure, such as `update_tree`, `delete_tree`, are called, as well as before creating, updating and moving nodes (see `save`, `_insert`, `_move_to `methods). This means that the cache is only invalidated when there is a change in the tree structure that could affect the data retrieved from cached methods.

Thus, the cache is indeed invalidated, but only in certain situations related to changes in the tree structure.

If you have questions about how this works or when exactly cache invalidation occurs, it's worth checking in what context caching is being used and seeing if tree modification methods are being called that might invalidate the cache.

**Comment by Wizely99** [comment]
I was getting the same results from `get_descendants_queryset` whether include_self was set to False or True, until I removed the `@cached_tree_method`. Additionally, I tried to locate where in the source code the cache is invalidated, but couldn't find it anywhere.

**Comment by Wizely99** [comment]
Also,I am considering contributing to the project. Are there any guidelines on which formatters to use for formatting the source code? I was thinking `black` and `isort` (for imports) could be perfect.

**Comment by TimurKady** [comment]
The issue you're experiencing with the get_descendants_queryset method, where results do not change despite different values of the `include_self `parameter, is indeed related to caching. The key problem is that cache identification does not include all method parameters. Specifically, the cache key generated by the @cached_tree_method decorator does not account for the `include_self` parameter, causing the method's results for different parameter values to be mistakenly regarded as identical. Consequently, the cache does not update when this parameter changes, leading to incorrect results.

To address this issue, one immediate workaround could be to manually clear the cache using `treenode_cache.clear()` before modifying the `include_self` setting. 

I'll consider enhancing the cache invalidation mechanisms to better handle such scenarios.

**Comment by TimurKady** [comment]
I'm not really adhering to any strict formatting standards on this project other than basic coding requirements. I'm more focused on the presence of comments and readability of the code, rather than strictly on its style.

However, I am open to suggestions and would consider using these tools if they improve the development process. How much do you think this can affect the usability of the project?

**Comment by TimurKady** [comment]
I have updated (added) the documentation with a section on using the cache.

**Comment by Wizely99** [comment]
i've seen the docs,thanks.
I'll be working on a PR for some improvements.
Hope to be done soon
